version: "3.7"
services:
  postgres:
    image: postgres:10.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  server:
    ports:
      - "3000:3000"
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/github-exporter
