version: "3.4"
services:
  postgres:
    image: postgres:10.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres-test
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
      target: builder

    depends_on:
      - postgres

    command: sh -c "npm test"

    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/github-exporter-test
